# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql

development:
  <<: *default
  database: twitter_dev

test:
  <<: *default
  database: twitter_test

production:
  adapter: postgresql
  database: twitter_prod
