default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  user: postgres
  password: FpvZYUqK9A8S

development:
  <<: *default
  database: twitterclone

test:
  <<: *default
  database: twitter_test

production:
  <<: *default
  database: twitterclone
